--1
select count(*) from student 
where St_Age is not null;

SELECT COUNT(St_Age) AS number_of_students
FROM Student;
--2
select distinct ins_name
from Instructor

--3
SELECT S.St_Id AS [Student ID],
ISNULL(S.St_Fname, '') + ' ' + ISNULL(S.St_Lname, '') AS Full_Name,
ISNULL(D.Dept_Name, 'No Department') AS [Deptartment name]
FROM Student S
LEFT JOIN Department D
ON S.Dept_Id = D.Dept_Id;

--4
SELECT I.Ins_Name AS Instructor_Name,
D.Dept_Name AS Department_Name
FROM Instructor I
LEFT JOIN Department D
ON I.Dept_Id = D.Dept_Id;

--5
SELECT CONCAT (ST_FNAME, ' ', ST_LNAME) AS FULLNAME,
CRS_NAME, GRADE
FROM STUDENT S
JOIN Stud_Course SC
ON S.St_Id = SC.St_Id
JOIN COURSE C
ON SC.Crs_Id = C.Crs_Id
WHERE SC.GRADE IS NOT NULL;


--6
SELECT TOP_NAME, COUNT(CRS_NAME) 
FROM TOPIC T
JOIN COURSE C
ON T.Top_Id = C.Top_Id
GROUP BY TOP_NAME;

--7
SELECT MAX(SALARY) AS [MAX SALARY], MIN(SALARY) AS [MIN SALARY]
FROM INSTRUCTOR;

--8
SELECT INS_NAME, SALARY
FROM INSTRUCTOR
WHERE SALARY < (SELECT AVG(SALARY) FROM INSTRUCTOR);

--9
SELECT DEPT_NAME 
FROM DEPARTMENT D
JOIN
INSTRUCTOR I
ON D.DEPT_ID = I.DEPT_ID
WHERE I.SALARY = (SELECT MIN(SALARY) FROM INSTRUCTOR);

--10
SELECT DISTINCT TOP 2 SALARY
FROM INSTRUCTOR
ORDER BY SALARY DESC;

--11
ALTER TABLE INSTRUCTOR 
ADD BONUS MONEY;

UPDATE INSTRUCTOR
SET BONUS = 5000;


SELECT INS_NAME ,
COALESCE (SALARY, BONUS) AS [instructor bonus]
FROM INSTRUCTOR;

--12
SELECT ST_FNAME, I.*
FROM STUDENT S
RIGHT JOIN
INSTRUCTOR I
ON S.ST_SUPER = I.Ins_Id
WHERE ST_FNAME IS NOT NULL;

--13
SELECT * FROM (
SELECT *, DENSE_RANK() OVER (PARTITION BY DEPT_ID ORDER BY SALARY DESC) AS RANKNUM
FROM INSTRUCTOR) AS NEWTABLE
WHERE RANKNUM <=2 AND SALARY IS NOT NULL;

--14
SELECT ST_FNAME, DEPT_ID FROM (
SELECT *, ROW_NUMBER() OVER (PARTITION BY DEPT_ID ORDER BY NEWID()) AS CHOSENSTUDENT
FROM Student 
WHERE DEPT_ID IS NOT NULL) AS NEWTABLEE
WHERE CHOSENSTUDENT = 1;


--15
DELETE SC
FROM Stud_Course SC
JOIN Student S
ON SC.St_Id = S.St_Id
JOIN Department D
ON S.Dept_Id = D.Dept_Id
WHERE D.Dept_Name = 'SD';


--16
