--1
SELECT DP.Dependent_name, DP.SEX
FROM DEPENDENT DP
JOIN
EMPLOYEE E
ON DP.ESSN = E.SSN
WHERE E.SEX = 'F' AND DP.SEX = 'F'
UNION ALL
SELECT DP.Dependent_name, DP.SEX
FROM DEPENDENT DP
JOIN
EMPLOYEE E
ON DP.ESSN = E.SSN
WHERE E.SEX = 'M' AND DP.SEX = 'M'

--2
SELECT P.PNAME, SUM(W.HOURS)
FROM PROJECT P
JOIN
WORKS_FOR W
ON P.Pnumber = W.PNO
GROUP BY PNAME;


--3
SELECT FNAME FROM EMPLOYEE
WHERE
SUPERSSN = (
SELECT SSN FROM EMPLOYEE
WHERE FNAME = 'KAMEL'
AND
LNAME = 'MOHAMED');

-- can be asnwered using self join as wellll

--3 /2

SELECT E.FNAME AS EMPLOYEE_NAME, S.FNAME AS SUPERVISOR
FROM EMPLOYEE E
JOIN EMPLOYEE S
ON E.SUPERSSN = S.SSN 
WHERE S.FNAME = 'KAMEL' AND S.LNAME = 'Mohamed';


--4
SELECT D.*
FROM DEPARTMENTS D
JOIN EMPLOYEE E ON D.DNUM = E.DNO
WHERE E.SSN = (SELECT MIN(SSN) FROM EMPLOYEE);

--5
SELECT D.DNAME, MAX(E.SALARY) AS MAX_SALARY, MIN(E.SALARY) AS MIN_SALARY, AVG(E.SALARY) AS AVG_SALARY
FROM DEPARTMENTS D
JOIN
EMPLOYEE E
ON D.DNUM = E.DNO
GROUP BY D.DNAME;

--6
SELECT CONCAT(M.FNAME, ' ', M.LNAME) AS MANAGERS
FROM EMPLOYEE M
JOIN
EMPLOYEE E
ON E.SUPERSSN = M.SSN

except

SELECT CONCAT(E.FNAME, ' ', E.LNAME)
FROM EMPLOYEE E 
JOIN
DEPENDENT DP
ON E.SSN = DP.ESSN

--momken another way :

--6/2

SELECT DISTINCT CONCAT(M.FNAME, ' ', M.LNAME) AS MANAGER_NAME
FROM EMPLOYEE M
JOIN EMPLOYEE E
ON E.SUPERSSN = M.SSN
LEFT JOIN DEPENDENT D
ON M.SSN = D.ESSN
WHERE D.ESSN IS NULL;


--7
SELECT DNAME, DNUM, COUNT(*) AS NUMBER_OF_EMP
FROM DEPARTMENTS D
JOIN 
EMPLOYEE E
ON D.DNUM = E.DNO
GROUP BY DNAME, DNUM
HAVING AVG(E.SALARY) < (SELECT AVG(SALARY) FROM EMPLOYEE);

--8
SELECT E.FNAME, E.LNAME, P.PNAME
FROM EMPLOYEE E 
JOIN
WORKS_FOR W
ON E.SSN = W.ESSn
JOIN
PROJECT P
ON W.Pno = P.Pnumber
ORDER BY E.DNO, E.Lname, E.Fname;


--9
SELECT TOP 2 SALARY FROM EMPLOYEE
ORDER BY SALARY DESC;

--9/2
SELECT SALARY
FROM EMPLOYEE
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE)

UNION

SELECT MAX(SALARY)
FROM EMPLOYEE
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)
ORDER BY SALARY DESC;


--10
SELECT CONCAT(E.FNAME, ' ', E.LNAME) AS FULLNAME
FROM EMPLOYEE E
JOIN 
DEPENDENT DP
ON E.SSN = DP.ESSN
WHERE DP.Dependent_name LIKE '%' + E.FNAME + '%'

--11
SELECT SSN, FNAME, LNAME
FROM EMPLOYEE E
WHERE EXISTS (
    SELECT 1
    FROM DEPENDENT D
);

--12
INSERT INTO DEPARTMENTS (DNUM, DNAME, MGRSSN, [MGRStart Date])
VALUES (100, 'DEPT IT', 112233, '2006-11-01');

--13

--a)
UPDATE DEPARTMENTS
SET MGRSSN = 968574, [MGRSTART DATE] = GETDATE()
WHERE DNUM = 100;

--b)
UPDATE DEPARTMENTS
SET MGRSSN = 102672, [MGRSTART DATE] = GETDATE()
WHERE DNUM = 20;

--c)
UPDATE EMPLOYEE
SET SUPERSSN = 102672
WHERE SSN = 102660 

--14
UPDATE EMPLOYEE
SET SUPERSSN = 102672  
WHERE SUPERSSN = 223344;


UPDATE DEPARTMENTS
SET MGRSSN = 102672,[MGRSTART DATE] = GETDATE()
WHERE MGRSSN = 223344;

UPDATE WORKS_FOR
SET ESSN = 102672  
WHERE ESSN = 223344;

DELETE FROM DEPENDENT
WHERE ESSN = 223344;

DELETE FROM EMPLOYEE
WHERE SSN = 223344;


--15
UPDATE EMPLOYEE
SET SALARY = SALARY * 1.3
FROM EMPLOYEE E
JOIN WORKS_FOR W
    ON E.SSN = W.ESSN
JOIN PROJECT P
    ON W.PNO = P.PNUMBER
WHERE P.PNAME = 'Al Rabwah';