USE Company_SD
--self join 
SELECT E.FNAME AS EMP_NAME, M.FNAME AS MANAGER
FROM EMPLOYEE E 
JOIN 
EMPLOYEE M
--ON "FK --> PK"
ON E.Superssn = M.SSN;


--GROUP BY : 
--🔑 أي عمود في SELECT مش معمول عليه Aggregate
-- يتحط في GROUP BY

SELECT MIN(SALARY), Dno
FROM EMPLOYEE
GROUP BY Dno;

SELECT ADDRESS, COUNT(*)
FROM EMPLOYEE
GROUP BY ADDRESS;

SELECT MAX(SALARY), DNO
FROM EMPLOYEE
WHERE ADDRESS IN('CAIRO', 'ALEX')
GROUP BY DNO;


/* 
EXECUTION ORDER:
1- FROM
2- JOIN
3-WHERE (FILTERING ROWS)
4- GROUP BY
5- AGGREGATION + HAVING
6- SELECT [DISTINCT, DISPLAY AGG]
7- ORDER BY
*/


-- SUBQUERRRR
-- SHOW EMP WHOS SALARY > AVG(SALARY)

SELECT * FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE WHERE SALARY IS NOT NULL);

UPDATE EMPLOYEE
SET SALARY *= 1.2
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEE);

--UNION FAMILY

--UNION ALL (MERGE 2 RESULTS)
SELECT FNAME 
FROM EMPLOYEE E
UNION ALL
SELECT DNAME
FROM DEPARTMENTS D


--UNION (ORDER + UNIQUE)
SELECT FNAME 
FROM EMPLOYEE E
UNION
SELECT DNAME
FROM DEPARTMENTS D

--EXCEPT (ORDERED + UNIQUE (NOT IN THE OTHER TABLE))
SELECT FNAME 
FROM EMPLOYEE E
EXCEPT
SELECT DNAME
FROM DEPARTMENTS D

--INTERSECT (SHARED RESULTS(UNIQUE + ORDERED))
SELECT FNAME 
FROM EMPLOYEE E
INTERSECT
SELECT DNAME
FROM DEPARTMENTS D

/* 

THE STRUCTURE OF RESULT COMING FROM THE FIRST TABLE SHOULD BE THE SAME AS THE SECOND ONE 
((1 COLUMN UNION 1 COLUMN))

*/


-- FUNCTIONS: 
-- CONCAT
SELECT CONCAT(FNAME,' ',LNAME) FROM Employee;

-- COALESCE
SELECT *
FROM EMPLOYEE
WHERE COALESCE(SALARY,0) > (SELECT AVG(COALESCE(SALARY,0)) FROM EMPLOYEE);

SELECT COALESCE(SALARY, 0) AS SALARY_NO_NULL
FROM EMPLOYEE;
--بدل ما نشتغل مع NULL → حطينا 0



--ISNULL
SELECT ISNULL(E.FNAME, 'NO VALUE')
FROM EMPLOYEE E;

